version: '3'

networks:
  whapi:

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOSTS=mysql
    ports:
      - ${PMA_PORT:-9000}:80
    networks:
      - whapi