version: '3'

networks:
  whapi:

services:

  backend:
    environment:
      - CHROME_WS=ws://chrome:5000

  chrome:
    image: browserless/chrome:latest
    environment:
      - MAX_CONCURRENT_SESSIONS=${MAX_CONCURRENT_SESSIONS:-1}
    networks:
      - whapi